- .github/workflows/test.yml
- README.md
> chore: enable codecov

- x/farming/keeper/reward.go
- x/farming/keeper/reward_test.go
> fix: skip zero total stakings when allocating rewards

- app/sim_test.go
- go.mod
- go.sum
- x/farming/keeper/reward.go
Since iteration order of map types is not deterministic, sort map keys before iteration.
> fix: sort map keys before iteration for deterministic execution

- x/claim/spec/02_state.md
- docs: fix typo in ConditionType spec 
---
> docs: review x/claim spec

- Makefile
> build: set ledger_enabled true as default on makefile

- x/claim/keeper/keeper_test.go
- x/liquidstaking/keeper/grpc_query.go
- x/liquidstaking/keeper/invariants.go
- x/liquidstaking/keeper/keeper_test.go
- x/liquidstaking/keeper/liquidstaking.go
- x/liquidstaking/keeper/liquidstaking_test.go
- x/liquidstaking/keeper/msg_server.go
- x/liquidstaking/keeper/rebalancing.go
- x/liquidstaking/keeper/rebalancing_test.go
- x/liquidstaking/keeper/tally_test.go
- x/liquidstaking/keeper/test_common.go
- x/liquidstaking/simulation/operations.go
- x/liquidstaking/simulation/proposals.go
- x/liquidstaking/types/expected_keepers.go
- x/liquidstaking/types/liquidstaking.go
- x/liquidstaking/types/params.go
- x/liquidstaking/types/params_test.go
- x/liquidstaking/types/rebalancing.go
- x/liquidstaking/types/rebalancing_test.go
> test: add logic and test for liquid unstaking edge cases

- x/liquidstaking/keeper/keeper_test.go
- x/liquidstaking/keeper/rebalancing.go
- x/liquidstaking/keeper/rebalancing_test.go
- x/liquidstaking/types/rebalancing.go
> fix: rebalancing logic to avoid redelegation restrictions

- x/mint/abci.go
- x/mint/keeper/keeper.go
> fix: fix typo on mint module

- x/claim/keeper/claim.go
- x/claim/keeper/claim_test.go
- x/claim/types/expected_keepers.go
> fix: fix gas consumption issue for vote condition type

- x/claim/module.go
- x/claim/simulation/operations.go
- x/claim/simulation/operations_test.go
- x/claim/types/expected_keepers.go
This PR fixes simulation logic for the `claim` module. It used to contain only `failures`. 
closes: #291
---
> fix: fix simulation for the `claim` module

- x/claim/client/cli/query.go
- x/farming/client/cli/query.go
- x/liquidity/client/cli/query.go
- x/liquidstaking/client/cli/query.go
> fix: fix to use query context

- x/liquidity/keeper/swap.go
- x/liquidity/keeper/swap_test.go
Since we now have new `IterateOrdersByOrderer` method, we can optimize `CancelAllOrders`.
Closes: #295
> fix: optimize CancelAllOrders gas usage

- docs/cli/claim.md
- docs/cli/farming.md
- docs/cli/liquidity.md
- docs/cli/liquidstaking.md
> docs: use Ignite CLI for Starport

- x/liquidity/amm/match.go
- x/liquidity/keeper/bench_test.go
- x/liquidity/keeper/swap_test.go
This PR fixes a bug in matching logic that was not considering zero order amount when deciding last matching price.
> fix: fix bug in matching logic

- docs/whitepapers/liquidity/pool.md
- x/liquidity/spec/01_concepts.md
- x/liquidity/spec/02_state.md
- x/liquidity/spec/04_messages.md
- x/liquidity/spec/07_events.md
> docs: add liquidity whitepaper (pool)

- docs/whitepapers/liquidity/matching.md
> docs: add liquidity module white paper (matching)

- Makefile
- go.mod
- go.sum
e.g. `make install COSMOS_BUILD_OPTIONS=rocksdb TENDERMINT_BUILD_OPTIONS=rocksdb BUILD_TAGS=rocksdb`
- 
---
> build: add dbbackend selection and bump tm-db

- x/liquidity/spec/01_concepts.md
- x/liquidity/spec/03_state_transitions.md
This PR adds links to the white paper about the matching process in the liquidity module.
-
- 
---
> docs: add links to the matching white paper

- .github/labeler.yml
- proto/squad/farming/v1beta1/query.proto
- proto/squad/liquidstaking/v1beta1/query.proto
- proto/squad/marketmaker/v1beta1/query.proto
- x/marketmaker/client/cli/query.go
- x/marketmaker/client/cli/tx.go
- x/marketmaker/keeper/marketmaker.go
- x/marketmaker/module.go
- x/marketmaker/simulation/decoder.go
- x/marketmaker/simulation/decoder_test.go
- x/marketmaker/simulation/genesis.go
- x/marketmaker/spec/05_events.md
- x/marketmaker/spec/06_params.md
- x/marketmaker/spec/07_proposal.md
- x/marketmaker/spec/README.md
- x/marketmaker/types/keys.go
> fix: minor semicolon proto, refactor marketmaker module

- go.mod
- go.sum
bump ibc-go from `v2.2.0-squad` to [`v2.2.0-squad-v3`](https://github.com/cosmosquad-labs/ibc-go/releases/tag/v2.2.0-squad-v3) which is patched to disable ibc transfer of pool coins ( starts with pool denom )
- https://github.com/cosmosquad-labs/ibc-go/releases/tag/v2.2.0-squad-v3
- https://github.com/cosmosquad-labs/ibc-go/compare/v2.2.0-squad...v2.2.0-squad-v3
- https://github.com/cosmosquad-labs/ibc-go/pull/2
---
> fix!: upgrade ibc-go for pool coin blacklisting

- config-test.yml
- docs/api/marketmaker.md
- docs/cli/marketmaker.md
- x/marketmaker/client/cli/tx.go
- x/marketmaker/client/cli/utils_test.go
This PR adds CLI and API documents for the `marketmaker` module.
---
> docs: add marketmakder docs

- docs/whitepapers/marketmaker/scoring.md
put latex line 36, 167
amend equation on line 56
no truncation from 86~123, 162~163, 169, 175~177
closes: #XXXX
- 
---
> docs: ameding equation on market maker scoring

- docs/whitepapers/marketmaker/scoring.md
Fix the example number as a result of considering the decimal point
- https://github.com/cosmosquad-labs/squad/pull/357
---
> docs: fix mm paper example number
